### ISSUE TITLE
Mismatch in project licenses

### ISSUE THREAD

**Issue by P3tras** [intino/itrules#1]
Hello,

Thanks for the great project. However, I was wondering what is the correct license type for it? Readme file says "itrules is licensed under the [LGPL](http://www.gnu.org/licenses/lgpl.html) v2.1. The LGPL guarantees that this library will stay open source, protecting your work"

However, the attached license file and Github About banner says that license is GPL3.0.

**Comment by octavioroncal** [comment]
Thanks. We have updated the licence to LGPL 3.0
